Add a quick ugly hack to avoid problems caused by zipfile.Path
Next week we'll work on a proper solution.

The error is on Python 3.10 with the following end of the stack trace:

```
  File "core/dataset_builder.py", line 368, in _checksums_path
    "tensorflow_datasets" in str(new_path)
  File "/<embedded stdlib>/zipfile.py", line 2391, in __str__
    return posixpath.join(self.root.filename, self.at)
  File "/<embedded stdlib>/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
PiperOrigin-RevId: 503649220